package com.zekodnix.zaramoney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdempotencyRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyRecordAllPropertiesEquals(IdempotencyRecord expected, IdempotencyRecord actual) {
        assertIdempotencyRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertIdempotencyRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyRecordAllUpdatablePropertiesEquals(IdempotencyRecord expected, IdempotencyRecord actual) {
        assertIdempotencyRecordUpdatableFieldsEquals(expected, actual);
        assertIdempotencyRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyRecordAutoGeneratedPropertiesEquals(IdempotencyRecord expected, IdempotencyRecord actual) {
        assertThat(actual)
            .as("Verify IdempotencyRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyRecordUpdatableFieldsEquals(IdempotencyRecord expected, IdempotencyRecord actual) {
        assertThat(actual)
            .as("Verify IdempotencyRecord relevant properties")
            .satisfies(a -> assertThat(a.getKeyHash()).as("check keyHash").isEqualTo(expected.getKeyHash()))
            .satisfies(a -> assertThat(a.getEndpoint()).as("check endpoint").isEqualTo(expected.getEndpoint()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getResponseBody()).as("check responseBody").isEqualTo(expected.getResponseBody()))
            .satisfies(a -> assertThat(a.getResponseStatus()).as("check responseStatus").isEqualTo(expected.getResponseStatus()))
            .satisfies(a ->
                assertThat(a.getTransactionReference()).as("check transactionReference").isEqualTo(expected.getTransactionReference())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdempotencyRecordUpdatableRelationshipsEquals(IdempotencyRecord expected, IdempotencyRecord actual) {
        // empty method
    }
}
