package com.zekodnix.zaramoney.domain;

import static com.zekodnix.zaramoney.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LedgerEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAllPropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertLedgerEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertLedgerEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAllUpdatablePropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertLedgerEntryUpdatableFieldsEquals(expected, actual);
        assertLedgerEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAutoGeneratedPropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryUpdatableFieldsEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getEntryType()).as("check entryType").isEqualTo(expected.getEntryType()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryUpdatableRelationshipsEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getTransaction()).as("check transaction").isEqualTo(expected.getTransaction()));
    }
}
