package com.zekodnix.zaramoney.domain;

import static com.zekodnix.zaramoney.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransactionFeeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionFeeAllPropertiesEquals(TransactionFee expected, TransactionFee actual) {
        assertTransactionFeeAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionFeeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionFeeAllUpdatablePropertiesEquals(TransactionFee expected, TransactionFee actual) {
        assertTransactionFeeUpdatableFieldsEquals(expected, actual);
        assertTransactionFeeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionFeeAutoGeneratedPropertiesEquals(TransactionFee expected, TransactionFee actual) {
        assertThat(actual)
            .as("Verify TransactionFee auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionFeeUpdatableFieldsEquals(TransactionFee expected, TransactionFee actual) {
        assertThat(actual)
            .as("Verify TransactionFee relevant properties")
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionFeeUpdatableRelationshipsEquals(TransactionFee expected, TransactionFee actual) {
        assertThat(actual)
            .as("Verify TransactionFee relationships")
            .satisfies(a -> assertThat(a.getTransaction()).as("check transaction").isEqualTo(expected.getTransaction()));
    }
}
