package com.zekodnix.zaramoney.domain;

import static com.zekodnix.zaramoney.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransactionRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRecordAllPropertiesEquals(TransactionRecord expected, TransactionRecord actual) {
        assertTransactionRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRecordAllUpdatablePropertiesEquals(TransactionRecord expected, TransactionRecord actual) {
        assertTransactionRecordUpdatableFieldsEquals(expected, actual);
        assertTransactionRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRecordAutoGeneratedPropertiesEquals(TransactionRecord expected, TransactionRecord actual) {
        assertThat(actual)
            .as("Verify TransactionRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRecordUpdatableFieldsEquals(TransactionRecord expected, TransactionRecord actual) {
        assertThat(actual)
            .as("Verify TransactionRecord relevant properties")
            .satisfies(a -> assertThat(a.getTransactionType()).as("check transactionType").isEqualTo(expected.getTransactionType()))
            .satisfies(a ->
                assertThat(a.getSendAmount())
                    .as("check sendAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSendAmount())
            )
            .satisfies(a ->
                assertThat(a.getReceiveAmount())
                    .as("check receiveAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getReceiveAmount())
            )
            .satisfies(a -> assertThat(a.getTransactionDate()).as("check transactionDate").isEqualTo(expected.getTransactionDate()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getSenderAccountNumber()).as("check senderAccountNumber").isEqualTo(expected.getSenderAccountNumber())
            )
            .satisfies(a ->
                assertThat(a.getReceiverAccountNumber()).as("check receiverAccountNumber").isEqualTo(expected.getReceiverAccountNumber())
            )
            .satisfies(a -> assertThat(a.getCurrencySendAmount()).as("check currencySendAmount").isEqualTo(expected.getCurrencySendAmount())
            )
            .satisfies(a ->
                assertThat(a.getCurrencyReceiveAmount()).as("check currencyReceiveAmount").isEqualTo(expected.getCurrencyReceiveAmount())
            )
            .satisfies(a -> assertThat(a.getTransactionStatus()).as("check transactionStatus").isEqualTo(expected.getTransactionStatus()))
            .satisfies(a ->
                assertThat(a.getTransactionReference()).as("check transactionReference").isEqualTo(expected.getTransactionReference())
            )
            .satisfies(a -> assertThat(a.getRiskScore()).as("check riskScore").isEqualTo(expected.getRiskScore()))
            .satisfies(a -> assertThat(a.getFraudStatus()).as("check fraudStatus").isEqualTo(expected.getFraudStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionRecordUpdatableRelationshipsEquals(TransactionRecord expected, TransactionRecord actual) {
        // empty method
    }
}
