package com.zekodnix.zaramoney.domain;

import static com.zekodnix.zaramoney.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TransactionLimitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLimitAllPropertiesEquals(TransactionLimit expected, TransactionLimit actual) {
        assertTransactionLimitAutoGeneratedPropertiesEquals(expected, actual);
        assertTransactionLimitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLimitAllUpdatablePropertiesEquals(TransactionLimit expected, TransactionLimit actual) {
        assertTransactionLimitUpdatableFieldsEquals(expected, actual);
        assertTransactionLimitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLimitAutoGeneratedPropertiesEquals(TransactionLimit expected, TransactionLimit actual) {
        assertThat(actual)
            .as("Verify TransactionLimit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLimitUpdatableFieldsEquals(TransactionLimit expected, TransactionLimit actual) {
        assertThat(actual)
            .as("Verify TransactionLimit relevant properties")
            .satisfies(a ->
                assertThat(a.getDailyLimit())
                    .as("check dailyLimit")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDailyLimit())
            )
            .satisfies(a ->
                assertThat(a.getMonthlyLimit())
                    .as("check monthlyLimit")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyLimit())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransactionLimitUpdatableRelationshipsEquals(TransactionLimit expected, TransactionLimit actual) {
        assertThat(actual)
            .as("Verify TransactionLimit relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()));
    }
}
