package com.zekodnix.zaramoney.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserDetailsAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAccountAllPropertiesEquals(UserDetailsAccount expected, UserDetailsAccount actual) {
        assertUserDetailsAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertUserDetailsAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAccountAllUpdatablePropertiesEquals(UserDetailsAccount expected, UserDetailsAccount actual) {
        assertUserDetailsAccountUpdatableFieldsEquals(expected, actual);
        assertUserDetailsAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAccountAutoGeneratedPropertiesEquals(UserDetailsAccount expected, UserDetailsAccount actual) {
        assertThat(actual)
            .as("Verify UserDetailsAccount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAccountUpdatableFieldsEquals(UserDetailsAccount expected, UserDetailsAccount actual) {
        assertThat(actual)
            .as("Verify UserDetailsAccount relevant properties")
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getFacePicture()).as("check facePicture").isEqualTo(expected.getFacePicture()))
            .satisfies(a -> assertThat(a.getIdCardPicture()).as("check idCardPicture").isEqualTo(expected.getIdCardPicture()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getIsAgent()).as("check isAgent").isEqualTo(expected.getIsAgent()))
            .satisfies(a -> assertThat(a.getKycStatus()).as("check kycStatus").isEqualTo(expected.getKycStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserDetailsAccountUpdatableRelationshipsEquals(UserDetailsAccount expected, UserDetailsAccount actual) {
        // empty method
    }
}
